language: node_js
cache: yarn
node_js:
- '6'
branches:
  only:
  - master
  - development
after_success:
- yarn run test:cover:travis
before_deploy:
- npm run deploybuild
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: website-2017.veryaustin.com
  skip_cleanup: true
  local-dir: "./dist"
  acl: public_read
  on:
    repo: veryaustin/veryaustin-2017-frontend
    branch: master
