export const FETCH_PAGE_BEGIN = "FETCH_PAGE_BEGIN";
export const FETCH_PAGE_SUCCESS = "FETCH_PAGE_SUCCESS";
export const FETCH_PAGE_ERROR = "FETCH_PAGE_ERROR";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
